assert-rs/assert_cmd

src/assert.rs
src/cargo.rs
src/cmd.rs
src/errors.rs
src/lib.rs
src/stdin.rs

Fixes #12
BREAKING CHANGE: This included moving all `cargo` stuff under a `cargo`
module in the public API.  The intent was to not add noise to the main
API with more tangential parts.  This might hide the extension trait too
much.  It might be added back to the root if this was found to confuse
people.

docs: Clarify the user's path through the docs

---

src/assert.rs
tests/cargo.rs

Fixes #2
BREAKING CHANGE: `stdout` / `stderr` now take a predicate by ownership.

feat(assert): Short-hand output predicates

---

src/assert.rs
tests/cargo.rs

Eventually `Predicate` is going to move into its own crate so any
breaking change to a predicate will not break `assert_fs`s API.  Having
predicates in the API foils that plan.

fix(assert): Don't put concrete predicates in the API

---

.travis.yml
src/assert.rs

Provide extra context on status failures (success, failure, interrupted,
code).  At the moment, the choice of whether to print stdout or stderr
is context specific.  I have a feeling this won't work as well as I'm
expecting but we'll start here.
Fixes #16

feat(assert): Context on status failures

---

Cargo.toml
examples/example_fixture.rs
src/bin/bin_fixture.rs
src/cargo.rs
src/errors.rs
src/lib.rs

This is to reduce the API surface to make maintaining compatibility easier.
Fixed #7

Remove `failure` from API

---

src/stdin.rs

This is a quick fix. I didn't carefully read the code. Please review before merge. Thanks.

Change with_stdin to &mut to fix #22

---

src/stdin.rs

There is just enough overlap between how people expect paths and strings
to be used, I felt we couldn't just have an `IntoStdIn`.
Long term, we should consider streaming the content from file / reader
to stdin.
Fixes #24
BREAKING CHANGE: `with_stdin(buffer)` is now
`with_stdin().buffer(buffer)`.

feat(stdin): Support piping in files

---

src/assert.rs
src/cargo.rs
src/cmd.rs
src/errors.rs
src/lib.rs
src/stdin.rs

Usually through documentation.

Improve API clarify

---

src/assert.rs
src/cargo.rs
src/cmd.rs
src/errors.rs
src/lib.rs

Some things I noticed while reading the docs.
One thing that confuses me are phrases like
> Assert the state of an [`Output`].
Where output is then linked to `std::process::Output`. Is this wise? The library is in theory generic over the output type. I changed the wording in the `OutputOkExt` trait docs, but I'm not entirely happy with it (it's too long).
I've also taken the liberty to simplifying a lot of markdown links to shortcut reference links. Once <https://github.com/rust-lang/rust/issues/43466> hits stable you can probably remove many of the link reference definitions.

Docs review

---

Cargo.toml
src/assert.rs
src/lib.rs
tests/assert.rs

While at it, fixed duplicate information being reported.
Fixes #8, #1

 feat(assert): Show cause of assert

---

Cargo.toml
src/cargo.rs
src/lib.rs
tests/cargo.rs

Fixes #44 except deciding what to do about target

 fix(cargo): Point people to escargot 

---

src/assert.rs
tests/assert.rs

fix(assert): Support Strings for easy comparison

---

src/cargo.rs

docs(cargo): List more caveats

---

.travis.yml
README.md
src/assert.rs
src/cargo.rs
src/cmd.rs
src/lib.rs
tests/assert.rs
tests/cargo.rs
tests/examples.rs

This is an experiemnt in a new direction in trying to resolve
- Cargo overhead (#6)
- Compile times from mismatched `--target` (#57)
- Suprising behavior if `--target <triplet>` isn't specified (#4)
The new downsides this introduces
- No `main_binary` or `cargo_example`
- Can only work within integration tests
We're recommending the use of `escargot` in these cases which I think
might be reasonable because instead of making policy decisions for the
user, and no one ever being happy, the user can choose which policy they
want.  Plus, in more complex cases they should already be using
`escargot` so they can cache.
Fixes #6
Fixes #57

perf(cargo): Faster bin lookup

---

src/cargo.rs
src/output.rs

`Error::description` has been documented as soft-deprecated since 1.27.0 (17 months ago). It is going to be hard-deprecated soon.
This PR:
- Removes an implementation of `description` in all error types
Related PR: https://github.com/rust-lang/rust/pull/66919

Remove deprecated Error::description

---

src/cargo.rs
src/output.rs

`Error::cause` has been documented as deprecated.
This PR removes `Error::cause` implementation
Related PR: https://github.com/assert-rs/assert_cmd/pull/86

Remove deprecated Error::cause

---

README.md

Currently the latest version is not listed in the `Cargo.toml` snippet. This causes the trivial example to fail as it requires the command wrapper listed in d159e875aee71841198c67cd1a4e848b8bb9e465.

fix(docs): List v0.12 in Cargo.toml snippet

---

src/lib.rs

:wave: 
I was giving this crate a try and ran into an issue with the first example so I thought I'd put up the fix. Thanks for taking a look! 
Before this commit, following the documentation's first example ended up in a compile
error because the `use` expression for the `Command` struct wasn't compatible with this crate's `0.11` version (the `Install` step says to use `assert_cmd = "0.11"`)
This is the error using `0.11` produces:
```
error[E0432]: unresolved import `assert_cmd::Command`
--> tests/tests.rs:2:5
|
2 | use assert_cmd::Command;
|     ^^^^^^^^^^^^^^^^^^^ no `Command` in the root
```
After this commit, the `use` expression is compatible with the crate.
Thanks for taking a look!

Bump example version for Cargo.toml dep

---

src/cmd.rs

fix(cmd): Don't deadlock between pipes

---

CONTRIBUTING.md

it looks like CONTRIBUTING.md was copied from
[stager](https://github.com/crate-ci/stager)
and the name was just never updated

fix: Typo stager -> assert_cmd

---

src/assert.rs
tests/assert.rs

Resolves: #104 
In the end I decided not to use the proposed generic version because it provided no crucial additional value.
It would be great if this pull request could be labeled with `hacktoberfest-accepted` (https://hacktoberfest.digitalocean.com/details) :grinning:

Add support for Vec<u8> as output expectation

---

CHANGELOG.md
release.toml
src/assert.rs

Users had to infer the reason for the panic based on the location.
Instead, we should tell them what failed so they can more quickly get up
and going on fixing it.
Fixes #109

fix(assert): Be explicit about spawn failure 

---

Cargo.toml
src/assert.rs
src/cmd.rs
src/output.rs

1. Even if stdout is not fully utf-8, we print all ASCII printable
characters verbatim and hex-escapes `\xAB` for non-printable
2. For inputs larger than 8KiB we only print first and last 2KiB and
omit bytes in the middle.
This helps reading error messages on larger stdin data (in my use case assert_cmd dumped ~440Mb of data on the terminal).

Better debug print of stdin

---

src/cargo.rs
src/lib.rs

docs: Fix escargot links

---

src/cargo.rs

This was added to cargo in 1.43 and should make our binary lookup more
reliable.  1.43 should be pretty wide spread but if someone hasn't
upgraded, then we'll still fall back to the old logic.
Fixes #101

fix(cargo): Take advantge of `CARGO_BIN_EXE`

---

src/assert.rs

Add `try_` variants of `Assert` methods

---

src/assert.rs
src/cmd.rs

Sorry, I should have run Clippy before submitting #128. My sincere apologies.

fix: Address `needles_borrow` warnings

---

src/assert.rs

Full disclosure: what is proposed is a **breaking change** for `assert_cmd`, so I won't be offended if it's rejected.
This PR (`*`) restricts `append_context`'s second argument (`context`) to be `Send + Sync`.
(`*`) will allow (`**`) instances of `Assert` to be `Send + Sync`.
And (`**`) combined with a PR to be submitted separately to `predicates-rs` will allow `AssertError`s (introduced in #128) to be converted to [`anyhow::Error`](https://docs.rs/anyhow/1.0.42/anyhow/struct.Error.html)s.
`anyhow::Error`'s requirement for `Send + Sync` is discussed [here](https://github.com/dtolnay/anyhow/issues/81).
Clearly, it would be untenable to break `assert_cmd` for every package it might be used with. But `anyhow` is pretty widely used. Moreover, the proposed bounds are relatively common and …

feat: Refine `append_context` bounds

---

.github/workflows/ci.yml
.github/workflows/rust-next.yml
CHANGELOG.md
src/assert.rs

Thanks to Rust 1.46, we can show the caller on panic, rather than
`assert_cmd`, as if `assert_cmd` was written with macros.
Fixes #133

fix(assert): Show caller on panic 

---

src/assert.rs

I'm in the process of writing integration tests with this awesome crate :) 
My tool is basically a CRUD cli for a distant API, and while writing tests I ran into this problem while testing deletions.
In some cases, i need to check the output of the `Assert` even if it succeeded when I expected a failure ( but that would work the other way around. 
An example : to verify a deletion process you'd do :delete, then read and expect an error : 
```rust
Command::cargo_bin("myTool")
.unwrap()
.arg("delete")
.arg("resource")
.assert()
.success();
Command::cargo_bin("myTool")
.unwrap()
.arg("read")
.arg("resource")
.assert()
.failure();
}
```
However in some cases the "read" operation succeed because the resource was not *yet* deleted by the remote system. 
I would need to check, because even if I …

feat: allow getting the Assert from an AssertError

---

src/output.rs

Fixes #137 (cc: @tailhook)
I implemented 6 from https://github.com/assert-rs/assert_cmd/issues/137#issuecomment-1356327217, since that seemed to be closest in spirit to the code that was already there.
Note: if a piece of text meets both the "too many lines" and "too many bytes" conditions, the former takes precedence, i.e., I display the text by omitting lines rather than bytes. My reasoning is: if a piece of text meets the "too many lines" condition, it is likely to also meet the "too many bytes" condition. In other words, if you didn't do it this way, this enhancement would almost never apply. The downside to this choice is that it could allow really long lines.

Restore newlines when writing `Bstr`s

---

src/assert.rs

It was probably just a finger slip.
I don't think it makes sense for it to be a dash and it's inconsistent with what is done in
https://github.com/assert-rs/assert_cmd/blob/ebf8e3e2f689fa1337e63637bc0d252da55fdf87/src/output.rs#L289

fix: Make message format consistent

---

README.md
build.rs
src/cargo.rs
tests/cargo.rs

allow to use assert_cmd with [cross](https://github.com/cross-rs/cross)
cross requires to use a runner to launch the binary. It configures cargo to run the binary
with that runner, so `cargo run --bin foo` works just fine, but assert_cmd doesn't do that
so the execution fails.
to test it on a x86_64 computer, just run `cross -v test --target aarch64-unknown-linux-gnu`
Fixes #139

Add cargo runner support in order to work with cross

---

src/cmd.rs

As discussed in #212, this adds the following getters that dispatch to the underlying `std::process::Command`
```rs
pub fn get_program(&self) -> &ffi::OsStr {}
pub fn get_args(&self) -> process::CommandArgs<'_> {}
pub fn get_envs<'a>(&'a self) -> process::CommandEnvs<'a> {}
pub fn get_current_dir(&self) -> Option<&path::Path> {}
```
This is my first rust PR, so apologies if anything is against convention.
@epage I'm not sure which additional getters you meant by
> plus ones specialized for the extra content in assert_cmd::Command.
as unless I'm missing something, there aren't any setters that aren't also in `std`
- Most of this is liberally copied from `std`, but I noticed many of the existing doc blocks were also either the same or had significant overlap. I'm happy to trim them down or …

feat: add getters to mirror those available on std::process::Command

---

src/cargo.rs
src/cmd.rs
src/lib.rs
src/macros.rs

This is prep for rust-lang/cargo#14125 which may break `fn cargo_bin`

feat(cargo): Add `cargo_bin!`
